var/www/symfony/practica4/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false,
     *     message="El nombre no puede contener numeros!!!!"
     * )
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false,
     *     message="El nombre no puede contener numeros!!!!"
     * )
     */
    private $apellidos;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_nacimiento;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $sexo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $foto;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ciudades", inversedBy="nombre_ciudad")
     */
    private $ciudad;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Aficiones", inversedBy="nombre_aficion")
     */
    private $aficion;

    public function __construct()
    {
        $this->aficion = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->nombre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getSexo(): ?string
    {
        return $this->sexo;
    }

    public function setSexo(string $sexo): self
    {
        $this->sexo = $sexo;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }

    public function getCiudad(): ?Ciudades
    {
        return $this->ciudad;
    }

    public function setCiudad(?Ciudades $ciudad): self
    {
        $this->ciudad = $ciudad;

        return $this;
    }

    /**
     * @return Collection|Aficiones[]
     */
    public function getAficion(): Collection
    {
        return $this->aficion;
    }

    public function addAficion(Aficiones $aficion): self
    {
        if (!$this->aficion->contains($aficion)) {
            $this->aficion[] = $aficion;
        }

        return $this;
    }

    public function removeAficion(Aficiones $aficion): self
    {
        if ($this->aficion->contains($aficion)) {
            $this->aficion->removeElement($aficion);
        }

        return $this;
    }
}

var/www/symfony/practica4/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre', TextType::class)
            ->add('apellidos', TextType::class)

            ->add('fecha_nacimiento', DateType::class, array(
                'widget' => 'single_text'

            ))

            ->add('sexo', ChoiceType::class, array(
                'choices' => array(

                    'Hombre' => 'Hombre',
                    'Mujer' => 'Mujer',

                ),
                'expanded' => true,
                'multiple' => false,
                'label' => 'Sexo',
                'required' => true
            ))

            ->add('foto', FileType::class, [
                'label' => 'Foto',
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Por favor introduce un formato de imagen válido',
                    ])
                ],
            ])
            ->add('email',EmailType::class)
            ->add('password', PasswordType::class)
            ->add('ciudad', EntityType::class, array(
                'required' => true,
                'label' => 'Ciudad de origen',
                'placeholder' => 'Selecciona ciudad...',
                'class' => 'App:Ciudades'
            ))
            ->add('aficion', null, [
                'multiple' => true,
                'expanded' => true,
                'label_attr' => ['class' => 'aficiones']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

var/www/symfony/practica4/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('foto')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($brochureFile) {
                $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $brochureFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $brochureFile->move(
                        $this->getParameter('files_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // actualiza la propiedad 'brochureFilename' para guardar el nombre archivo
                $user->setFoto($newFilename);
            }

            $user->setPassword($passwordEncoder->encodePassword($user, $form['password']->getData()));

            $user->setRoles(['ROLE_ADMIN']);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            // ... persist the $product variable or any other work

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('foto')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($brochureFile) {
                $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $brochureFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $brochureFile->move(
                        $this->getParameter('files_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // actualiza la propiedad 'brochureFilename' para guardar el nombre archivo
                $user->setFoto($newFilename);
            }
            $user->setPassword($passwordEncoder->encodePassword($user, $form['password']->getData()));
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

var/www/symfony/practica4/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Seguro que quieres borrar al usuario?!?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-primary" id="btnUsu">Eliminar</button>
</form>

var/www/symfony/practica4/templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

var/www/symfony/practica4/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar usuario{% endblock %}

{% block body %}
    <h1 align="center">Editar usuario</h1>
    <div id="div1_2">
        {{ include('user/_form.html.twig', {'button_label': 'Actualizar'}) }}
        <div id="centrarBotones1">
        <a href="{{ path('user_index') }}" class="btn btn-primary">Volver a la lista</a>

        {{ include('user/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

var/www/symfony/practica4/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tabla de usuarios
{% endblock %}

{% block body %}
    <h1 align="center">Tabla de usuarios</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Email</th>
				<th>Nombre</th>
				<th>Apellidos</th>
				<th>Fecha_nacimiento</th>
				<th>Sexo</th>
				<th>Ciudad</th>
				<th>Aficion</th>
				<th>Foto</th>
				<th>Accion</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
				<tr>
					<td>{{ user.email }}</td>
					<td>{{ user.nombre }}</td>
					<td>{{ user.apellidos }}</td>
					<td>{{ user.fechaNacimiento ? user.fechaNacimiento|date('d-M-y') : '' }}</td>
					<td>{{ user.sexo }}</td>
					<td>
						{% if user.ciudad == null %}
							{{ "Ciudad eliminada" }}
						{% else %}
							{{ user.ciudad }}
						{% endif %}
					</td>
					<td>
						<ul>
							{% for aficion in user.getAficion() %}
								<li>{{ aficion }}</li>
							{% else %}
								<li>{{ "Sin aficiones" }}</li>
							{% endfor %}
						</ul>
					</td>
					<td>
						<img src="{{ asset( user.foto , 'imagenUsu') }}" class="img-fluid logo" alt="imagen_not_found">
					</td>
					<td>
						<a href="{{ path('user_show', {'id': user.id}) }}" class="btn btn-primary">Mostrar</a>
						<a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-primary">Editar</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="10">No hay Registros</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<a href="{{ path('user_new') }}" class="btn btn-primary">Crear nuevo</a>
{% endblock %}

var/www/symfony/practica4/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulario Nuevos Usuarios{% endblock %}

{% block body %}
    <h1 align="center">Formulario nuevos usuarios</h1>
    <br>
    <div id="div1_2">
        <div id="centrarBotones">
        {{ include('user/_form.html.twig') }}
        </div>
    <a href="{{ path('user_index') }}" class="btn btn-primary">Volver a la lista</a>
    </div>
     
{% endblock %}

var/www/symfony/practica4/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario
{% endblock %}

{% block body %}
	<h1 align="center">Datos personales</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Email</th>
				<td>{{ user.email }}</td>
			</tr>
			<tr>
				<th>Password</th>
				<td>***</td>
			</tr>
            <tr>
				<th>Nivel de acceso</th>
				<td>
					<ul>
						{% for roles in user.getRoles() %}
							<li>{{ roles }}</li>
						{% else %}
							<li>{{ "No tiene roles" }}</li>
						{% endfor %}
					</ul>
				</td>
			</tr>
			<tr>
				<th>Nombre</th>
				<td>{{ user.nombre }}</td>
			</tr>
			<tr>
				<th>Apellidos</th>
				<td>{{ user.apellidos }}</td>
			</tr>
			<tr>
				<th>Fecha de nacimiento</th>
				<td>{{ user.fechaNacimiento ? user.fechaNacimiento|date('d-m-Y') : '' }}</td>
			</tr>
			<tr>
				<th>Ciudad de origen</th>
				<td>{{user.ciudad}}</td>
			</tr>
			<tr>
				<th>Sexo</th>
				<td>{{ user.sexo }}</td>
			</tr>
			<tr>
				<th>Aficiones</th>
				<td>
					<ul>
						{% for aficion in user.getAficion() %}
							<li>{{ aficion }}</li>
						{% else %}
							<li>{{ "No tiene aficiones" }}</li>
						{% endfor %}
					</ul>
				</td>
			</tr>
            <tr>
				<th>Foto</th>
				<td>
					<img src="{{ asset( user.foto , 'imagenUsu') }}" class="img-fluid logo" alt="imagen_not_found">
				</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('user_index') }}" class="btn btn-primary" id="btnUsu">Volver a la lista</a>

	<a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-primary" id="btnUsu">Editar</a>

	{{ include('user/_delete_form.html.twig') }}
{% endblock %}